# Generated by Django 4.2.28 on 2026-03-17 01:18

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("organizer", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="Fecha de creación",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="category",
            name="slug",
            field=models.SlugField(
                blank=True,
                help_text="URL-friendly version del nombre (generado automáticamente)",
                unique=True,
            ),
        ),
        migrations.AddField(
            model_name="category",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, verbose_name="Fecha de actualización"
            ),
        ),
        migrations.AddField(
            model_name="resource",
            name="slug",
            field=models.SlugField(
                blank=True, help_text="URL-friendly version del título", unique=True
            ),
        ),
        migrations.AddField(
            model_name="resource",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, verbose_name="Fecha de actualización"
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="Descripción detallada de la categoría",
                verbose_name="Descripción",
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(
                help_text="Nombre único de la categoría",
                max_length=100,
                unique=True,
                verbose_name="Nombre",
            ),
        ),
        migrations.AlterField(
            model_name="resource",
            name="category",
            field=models.ForeignKey(
                help_text="Categoría a la que pertenece este recurso",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="resources",
                to="organizer.category",
                verbose_name="Categoría",
            ),
        ),
        migrations.AlterField(
            model_name="resource",
            name="description",
            field=models.TextField(
                help_text="Descripción detallada del recurso",
                verbose_name="Descripción",
            ),
        ),
        migrations.AlterField(
            model_name="resource",
            name="priority",
            field=models.CharField(
                choices=[("alta", "Alta"), ("media", "Media"), ("baja", "Baja")],
                default="media",
                help_text="Nivel de prioridad del recurso",
                max_length=10,
                verbose_name="Prioridad",
            ),
        ),
        migrations.AlterField(
            model_name="resource",
            name="status",
            field=models.CharField(
                choices=[
                    ("pendiente", "Pendiente"),
                    ("revisado", "Revisado"),
                    ("importante", "Importante"),
                ],
                default="pendiente",
                help_text="Estado actual del recurso",
                max_length=20,
                verbose_name="Estado",
            ),
        ),
        migrations.AlterField(
            model_name="resource",
            name="title",
            field=models.CharField(
                help_text="Título descriptivo del recurso",
                max_length=150,
                verbose_name="Título",
            ),
        ),
        migrations.AlterField(
            model_name="resource",
            name="url",
            field=models.URLField(
                blank=True,
                help_text="URL del recurso (opcional)",
                null=True,
                verbose_name="Enlace",
            ),
        ),
        migrations.AddIndex(
            model_name="category",
            index=models.Index(fields=["name"], name="organizer_c_name_3cfc9c_idx"),
        ),
        migrations.AddIndex(
            model_name="category",
            index=models.Index(fields=["slug"], name="organizer_c_slug_68158c_idx"),
        ),
        migrations.AddIndex(
            model_name="resource",
            index=models.Index(fields=["title"], name="organizer_r_title_f0b218_idx"),
        ),
        migrations.AddIndex(
            model_name="resource",
            index=models.Index(fields=["status"], name="organizer_r_status_083754_idx"),
        ),
        migrations.AddIndex(
            model_name="resource",
            index=models.Index(
                fields=["priority"], name="organizer_r_priorit_9154f3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="resource",
            index=models.Index(
                fields=["category"], name="organizer_r_categor_87cd56_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="resource",
            index=models.Index(
                fields=["-created_at"], name="organizer_r_created_706ec3_idx"
            ),
        ),
    ]
